### PR TITLE
User card

### PR DESCRIPTION
**Pull request by BertrandVouillot**

### CODE REVIEW

**Comment by valeriangalliat** [comment]
I merged this this morning, why do you submit it again?
<sup><sub><a href="https://irc.codejam.info/?channels=#general">Discuss here</a></sub></sup>

**Comment by Garcia6l20** [comment]
- bug : rc/MediaBundle/Resources/views/menuadmin.html.twig:179,83 : ~~entity.sec~~ -> entity.sex

**Comment by Garcia6l20** [comment]
- bug : again a failing dql request ... : AdminController::indexAction

I didn't identified the reason yet, the error :

``` SQL
An exception occurred while executing 'SELECT d0_.word AS word0, COUNT(d1_.id) AS sclr1 FROM dio_mediakeyword d0_ INNER JOIN dio_mediakeywords_media d2_ ON d0_.id = d2_.keyword_id INNER JOIN dio_media d1_ ON d1_.id = d2_.media_id GROUP BY d1_.id ORDER BY sclr1 DESC LIMIT 10':

SQLSTATE[42803]: Grouping error: 7 ERROR: column "d0_.word" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT d0_.word AS word0, COUNT(d1_.id) AS sclr1 FROM dio_me...
```

**Comment by AJahJahRiddim** [comment]
Bug fix pushed [here](https://github.com/ariescdi/documentio/commit/9e6608e4dc2003f45c56002e0bd5974afc237a41)

**Comment by valeriangalliat** [comment]
Don't commit here, the PR was already merged, with conflict fixes. I can't merge it again.

**Comment by Garcia6l20** [comment]
Cannot change my sex in Card edit :(

**Pull request closed without merging**
